#!/usr/bin/env bash

SWIFT_MACHINE_USERNAME="${SWIFT_MACHINE_USERNAME:?Please set the username for the machine which has the needed libraries in the SWIFT_MACHINE_USERNAME environment variable}"
SWIFT_MACHINE_ADDRESS="${SWIFT_MACHINE_ADDRESS:?Please set the machine address of the machine which has the needed libraries in the SWIFT_MACHINE_ADDRESS environment variable}"

scp ${SWIFT_MACHINE_USERNAME}@${SWIFT_MACHINE_ADDRESS}:swift/swift-android-toolchain/usr/lib/swift/android/{libswiftCore.so,libswiftSwiftOnoneSupport.so} armeabi-v7a
scp ${SWIFT_MACHINE_USERNAME}@${SWIFT_MACHINE_ADDRESS}:swift/swift-android-toolchain/usr/lib/swift/android/armv7/{libc++_shared.so,libicudataswift.so,libicui18nswift.so,libicuucswift.so} armeabi-v7a

adb push armeabi-v7a/{libswiftCore.so,libswiftSwiftOnoneSupport.so,libc++_shared.so,libicudataswift.so,libicui18nswift.so,libicuucswift.so} /data/local/tmp

scp ${SWIFT_MACHINE_USERNAME}@${SWIFT_MACHINE_ADDRESS}:android/AmrSwiftAndroid/HelloAndroid/hello .
adb push hello /data/local/tmp

