#!/bin/bash

set -e

: ${SWIFT_MACHINE_ADDRESS?}
: ${SWIFT_MACHINE_USERNAME?}

mkdir -p armeabi-v7a
scp ${SWIFT_MACHINE_USERNAME}@${SWIFT_MACHINE_ADDRESS}:android/SwiftAndroid/AddSwiftLib/output/armeabi-v7a/libAddSwift.so armeabi-v7a
