#!/bin/bash

set -e

: ${SWIFT_MACHINE_USERNAME?}
: ${SWIFT_MACHINE_ADDRESS?}

scp ${SWIFT_MACHINE_USERNAME}@${SWIFT_MACHINE_ADDRESS}:android/libs/armeabi-v7a/libAddSwift.so ${ANDROID_LIBS_DIR}/armeabi-v7a
